name: Continuous Integration of WEBAPP

on:
  pull_request:
    branches:
      - main

jobs:
  packer:
    name: Packer Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: 'latest'

      - name: Initialize Packer Plugins
        run: |
          echo "Initializing Packer plugins for source.pkr.hcl"
          packer init packer/source.pkr.hcl
          echo "Initializing Packer plugins for build.pkr.hcl"
          packer init packer/build.pkr.hcl

      - name: Run Packer Validate
        run: |
          packer validate packer/build.pkr.hcl
          packer validate packer/source.pkr.hcl
        continue-on-error: false

      - name: Run Packer validate recursively
        run: |
          for file in $(find packer -name "*.pkr.hcl"); do
            echo "Validating $file"
            packer validate "$file" || (echo "Packer validation failed for $file." && exit 1)
          done
        continue-on-error: false
