name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer:
    name: Packer Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: 'latest'

      - name: Verify Packer Installation
        run: |
          packer --version
          which packer

      - name: Create JSON File from Secret
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' | jq '.' > secret.json

      - name: Initialize Packer Plugins
        run: |
          echo "Initializing Packer plugins for source.pkr.hcl"
          packer init -upgrade packer/

      - name: Packer Format Check  
        run: |
          echo "Running packer fmt to format HCL files..."
          packer fmt -check -diff -recursive packer/

      - name: Run Packer Validate
        run: |
          packer validate \
          -var "mysql_password=${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          -var "ami_users=[\"000000000000\"]" \
          -var "credentials_file=secret.json" \
          -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
          packer/

