name: Continuous Integration Of WEBAPP

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Continuous Integration WEBAPP
    runs-on: ubuntu-latest
    environment: dev

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Configure Environment Variables
        run: |
          echo "DATABASE_URL=mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:3306/${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV

      
      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h "${{ secrets.DB_HOST }}" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Run Database Migrations
        run: node db.js

      - name: Run Tests
        run: npm test -- --forceExit
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          PORT: ${{ env.PORT }}