name: Continuous Integration of WEBAPP
 
on:
  pull_request_target:
    branches:
      - main
 
jobs:
  build:
    name: Continuous Integration WEBAPP
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Create and Set Environment Variables
        shell: bash
        working-directory: ./src
        run: |
          touch .env
          echo "DATABASE_URL=mysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_ROOT_PASSWORD }}@localhost:3306/${{ secrets.MYSQL_DATABASE }}" >> .env

      - name: Install Dependencies
        run: npm install
        working-directory: ./src
 
      - name: Start GitHub-Hosted MySQL
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql || true  # Ignore errors in status check

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {30..0}; do
            if mysqladmin ping -h "localhost" --silent; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "⏳ Waiting for MySQL to start... ($i seconds remaining)"
            sleep 2
          done

          # Final Check: If MySQL is still not responding, fail the job
          if ! mysqladmin ping -h "localhost" --silent; then
            echo "❌ MySQL did not start in time."
            exit 1
          fi

      - name: Configure Database & User
        run: |
          sudo mysql -uroot -proot <<EOF
          CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};
          CREATE USER IF NOT EXISTS '${{ secrets.MYSQL_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';
          GRANT ALL PRIVILEGES ON ${{ secrets.MYSQL_DATABASE }}.* TO '${{ secrets.MYSQL_USER }}'@'localhost';
          FLUSH PRIVILEGES;
          EOF
 
      - name: Debug Database Connection
        run: |
          echo "Checking MySQL connection using credentials from GitHub Secrets..."
          mysql -u${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"

      - name: Run Tests
        working-directory: ./src
        run: npm test
        env:
          DATABASE_URL: mysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_ROOT_PASSWORD }}@localhost:3306/${{ secrets.MYSQL_DATABASE }}
